server:
  port: 9940
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      charset: UTF-8
      force: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery:123456@127.0.0.1:9920/eureka/,http://discovery:123456@127.0.0.1:9930/eureka/
  instance:
    prefer-ip-address: true

turbine:
  app-config: xlaoy-server,nmh-gateway
  cluster-name-expression: xlaoy